name: mlflow-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow==3.7.0
      - scikit-learn==1.7.2
      - pandas==2.3.3
      - numpy==2.2.6
      - cloudpickle
      - matplotlib
      - seaborn
