# -*- coding: utf-8 -*-
"""modelling

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LitqNTNjJiwRNIczzmfJktxpROKatU5n
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
!pip install dagshub
!pip install mlflow
import mlflow
import mlflow.sklearn
import dagshub

# =============================
# CONFIG
# =============================
DATA_PATH = "Membangun_Model/churn_preprocessed.csv"
EXPERIMENT_NAME = "Customer Churn Prediction"

# =============================
# INIT DAGSHUB + MLFLOW
# =============================
dagshub.init(
    repo_owner="nyomanarinit",
    repo_name="Membangun_Model",
    mlflow=True
)

mlflow.set_experiment(EXPERIMENT_NAME)

# =============================
# LOAD DATA
# =============================
print("🚀 Proses training dimulai...")

df = pd.read_csv(DATA_PATH)

X = df.drop("Exited", axis=1)
y = df["Exited"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# =============================
# SCALING
# =============================
from sklearn.preprocessing import MinMaxScaler # Added this import
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# =============================
# MLFLOW AUTOLOG
# =============================
mlflow.sklearn.autolog(log_input_examples=True)

# =============================
# TRAIN MODEL
# =============================
with mlflow.start_run(run_name="RandomForest-Basic"):
    model = RandomForestClassifier(random_state=42)
    model.fit(X_train_scaled, y_train)

print("✅ Training selesai & otomatis tercatat di MLflow")